/*
* Copyright 2016 Samsung Research America. All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
package com.samsung.sra.datastore;

import java.io.Serializable;

/**
 * Generate a sequence of window lengths, e.g. 1, 2, 4, 8, ...
 */
public interface WindowLengthsSequence extends Serializable {
    long nextWindowLength();

    /** Size of the largest possible window generated by this sequence (Long.MAX_VALUE if unbounded) */
    default long maxWindowSize() {
        return Long.MAX_VALUE;
    }
}
