package com.samsung.sra.datastore;

import java.io.Serializable;

/**
 * Generate a sequence of window lengths, e.g. 1, 2, 4, 8, ...
 */
public interface WindowLengthsSequence extends Serializable {
    long nextWindowLength();

    /** Size of the largest possible window generated by this sequence (Long.MAX_VALUE if unbounded) */
    default long maxWindowSize() {
        return Long.MAX_VALUE;
    }
}
